### PR TITLE
Get matching colnames

### PR DESCRIPTION
**Pull request by NikitaShymberg**
Implemented the function and the tests. I'm less comfortable with R than Python, so don't be afraid to point out improvements!

### CODE REVIEW

**Review by SonQBChau — COMMENTED** [review]
The code pass when I run test(), but throw error 
`Error in `str_match(colnames(df), pattern)`: could not find function "str_match"`
when I use check().
I'm not sure if this is the problem with my machine only. Can you double check?

**Comment by NikitaShymberg** [comment]
Hmmm... it worked on my machine! Maybe we need to add `stringr` as a dependency or something. I'll look into it tomorrow morning!

**Comment by NikitaShymberg** [comment]
I think this should work now?

**Comment by SonQBChau** [comment]
It's good now. You can merge :white_check_mark:

**Comment by NikitaShymberg** [comment]
Could you approve the PR? Until someone approves, merging is blocked.

**Review by SonQBChau — APPROVED** [review]

**Pull request merged**
