### PR TITLE
Implement percent change

### LINKED ISSUE #19: feats: test calculate_percentage_change function

### LINKED ISSUE #20: feats: implement calculate_percentage_change function

### PR DESCRIPTION
**Pull request by veerupandey**
1. Implement percent change
2. Add test cases
3. Add relevant packages

### CODE REVIEW

**Review by SonQBChau — COMMENTED** [review]
I got these error when running test(). Could you see if that happen on your end also?
```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-calculate_percentage_change.R:61:3): Check retrurn type
Error in `calculate_percentage_change(test_df, "data_usage")`: Sum of start period and end period must not exceed total number of columns
Backtrace:
 1. testthat::expect_type(...) test-calculate_percentage_change.R:61:2
 4. featurescreator::calculate_percentage_change(test_df, "data_usage")

Error (test-calculate_percentage_change.R:66:3): Check return type
Error in `calculate_percentage_change(test_df, "data_usage", compare_period = c(1, 
    1), time_filter = c(1, 3))`: Column pattern from time_filter is not present in all columns
Backtrace:
 1. testthat::expect_type(...) test-calculate_percentage_change.R:66:2
 4. featurescreator::calculate_percentage_change(...)

Error (test-calculate_percentage_change.R:81:13): Percentage change with default parameters
Error in `calculate_percentage_change(test_df, "data_usage")`: Sum of start period and end period must not exceed total number of columns
Backtrace:
 1. testthat::expect_equal(...) test-calculate_percentage_change.R:81:12
 4. featurescreator::calculate_percentage_change(test_df, "data_usage")

Error (test-calculate_percentage_change.R:89:13): Percentage change with compare periods
Error in `calculate_percentage_change(test_df, "data_usage", compare_period = c(1, 
    2))`: Sum of start period and end period must not exceed total number of columns
Backtrace:
 1. testthat::expect_equal(...) test-calculate_percentage_change.R:89:12
 4. featurescreator::calculate_percentage_change(...)

Error (test-calculate_percentage_change.R:100:3): Percentage change with time filter
Error in `calculate_percentage_change(test_df, "data_usage", compare_period = c(1, 
    2), time_filter = c(1, 3, 4))`: Column pattern from time_filter is not present in all columns
Backtrace:
 1. testthat::expect_equal(...) test-calculate_percentage_change.R:100:2
 4. featurescreator::calculate_percentage_change(...)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
[ FAIL 5 | WARN 0 | SKIP 0 | PASS 6 ]
```

**Comment by SonQBChau** [comment]
Sorry I didn't see the Work in Progress, ignore my comment above if it's not ready for review

**Comment by veerupandey** [comment]
Ready for review.

**Comment by NikitaShymberg** [comment]
Looks great! The tests passed on my system and the code looks good to me.

**Review by NikitaShymberg — APPROVED** [review]

**Pull request merged**
